ALTER TABLE "image_brief" DROP CONSTRAINT "ck_image_brief_source_projection_owner";--> statement-breakpoint
ALTER TYPE "public"."image_source_projection_kind" RENAME TO "image_source_projection_kind_old";--> statement-breakpoint
CREATE TYPE "public"."image_source_projection_kind" AS ENUM('rss_extract', 'rss_feed', 'telegram_post', 'promo_idea');--> statement-breakpoint
ALTER TABLE "image_brief" ALTER COLUMN "source_projection_kind" TYPE "public"."image_source_projection_kind" USING "source_projection_kind"::text::"public"."image_source_projection_kind";--> statement-breakpoint
DROP TYPE "public"."image_source_projection_kind_old";--> statement-breakpoint
ALTER TABLE "image_brief" ADD COLUMN "rss_source_item_revision_id" uuid;--> statement-breakpoint
ALTER TABLE "image_brief" ADD COLUMN "rss_content_hash" text;--> statement-breakpoint
ALTER TABLE "image_brief" ADD CONSTRAINT "fk_image_brief_rss_source_item_revision_id" FOREIGN KEY ("rss_source_item_revision_id") REFERENCES "public"."source_item_revision"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "image_brief" ADD CONSTRAINT "ck_image_brief_source_projection_owner" CHECK (("image_brief"."source_projection_kind" = 'rss_extract' and "image_brief"."rss_source_item_enrichment_id" is not null and "image_brief"."rss_page_content_hash" is not null and "image_brief"."rss_source_item_revision_id" is null and "image_brief"."rss_content_hash" is null and "image_brief"."telegram_source_item_revision_id" is null and "image_brief"."telegram_content_hash" is null and "image_brief"."promo_idea_id" is null) or ("image_brief"."source_projection_kind" = 'rss_feed' and "image_brief"."rss_source_item_enrichment_id" is null and "image_brief"."rss_page_content_hash" is null and "image_brief"."rss_source_item_revision_id" is not null and "image_brief"."rss_content_hash" is not null and "image_brief"."telegram_source_item_revision_id" is null and "image_brief"."telegram_content_hash" is null and "image_brief"."promo_idea_id" is null) or ("image_brief"."source_projection_kind" = 'telegram_post' and "image_brief"."rss_source_item_enrichment_id" is null and "image_brief"."rss_page_content_hash" is null and "image_brief"."rss_source_item_revision_id" is null and "image_brief"."rss_content_hash" is null and "image_brief"."telegram_source_item_revision_id" is not null and "image_brief"."telegram_content_hash" is not null and "image_brief"."promo_idea_id" is null) or ("image_brief"."source_projection_kind" = 'promo_idea' and "image_brief"."rss_source_item_enrichment_id" is null and "image_brief"."rss_page_content_hash" is null and "image_brief"."rss_source_item_revision_id" is null and "image_brief"."rss_content_hash" is null and "image_brief"."telegram_source_item_revision_id" is null and "image_brief"."telegram_content_hash" is null and "image_brief"."promo_idea_id" is not null));
