import { z } from "zod";

const OPERATION_ERROR_CODES = [
  "OPERATION_REPLAYED",
  "IDEMPOTENCY_KEY_REUSED",
  "VALIDATION_FAILED",
  "UNAUTHORIZED",
  "FORBIDDEN",
  "NOT_FOUND",
  "VERSION_CONFLICT",
  "SAVED_CARD_ALREADY_ACTIVE",
  "TRANSIENT_CONFLICT",
  "TEMPLATE_DRIFT",
  "MODEL_INVOCATION_FAILED",
  "STRUCTURED_OUTPUT_INVALID",
  "IMAGE_SOURCE_EXTRACT_REQUIRED",
  "OBJECT_STORE_UNBOUND",
  "MEDIA_REJECTED",
  "SOURCE_IMPORT_IN_PROGRESS",
  "MARKET_ANALYSIS_COMPLETED",
  "MARKET_ANALYSIS_NOT_READY",
  "MARKET_SNAPSHOT_UNVERIFIED",
  "MARKET_SERIES_UNAVAILABLE",
  "MARKET_CHART_RENDER_FAILED",
  "MARKET_GENERATION_FAILED",
  "MARKET_GENERATION_UNKNOWN",
  "MARKET_FINALIZATION_FAILED",
  "INTERNAL_SERVER_ERROR",
] as const;

const PUBLICATION_FAILURE_BASE_CODES = [
  "MEDIA_NOT_PUBLISHABLE",
  "PUBLISH_PAYLOAD_TOO_LONG",
  "DELIVERY_DEFINITELY_FAILED",
  "DELIVERY_UNKNOWN",
  "PROVIDER_RATE_DEFERRED",
  "PROVIDER_AUTH_FAILED",
  "PROVIDER_CAPABILITY_UNAVAILABLE",
] as const;

const PROVIDER_SPECIFIC_FAILURE_CODES = [
  "TELEGRAM_DELIVERY_UNKNOWN",
  "TELEGRAM_RATE_LIMITED",
  "TELEGRAM_CHANNEL_MIGRATED",
  "TELEGRAM_REQUEST_INVALID",
  "TELEGRAM_AUTH_FAILED",
  "TELEGRAM_POSTING_FORBIDDEN",
  "X_MEDIA_PREPARATION_UNKNOWN",
  "X_DELIVERY_UNKNOWN",
  "X_REQUEST_INVALID",
  "X_AUTH_FAILED",
  "X_CAPABILITY_UNAVAILABLE",
  "X_RATE_LIMITED",
  "INSTAGRAM_CAPACITY_UNAVAILABLE",
  "INSTAGRAM_RATE_LIMITED",
  "INSTAGRAM_CONTAINER_PREPARATION_UNKNOWN",
  "INSTAGRAM_CONTAINER_PROCESSING_DELAYED",
  "INSTAGRAM_CONTAINER_STATUS_UNKNOWN",
  "INSTAGRAM_CONTAINER_EXPIRED",
  "INSTAGRAM_CONTAINER_FAILED",
  "INSTAGRAM_DELIVERY_UNKNOWN",
  "INSTAGRAM_REQUEST_INVALID",
  "INSTAGRAM_AUTH_FAILED",
  "INSTAGRAM_CAPABILITY_UNAVAILABLE",
] as const;

export type ErrorCode = (typeof OPERATION_ERROR_CODES)[number];

export const errorCodeSchema = z.enum(OPERATION_ERROR_CODES);

export const PUBLICATION_FAILURE_CODES = [
  ...PUBLICATION_FAILURE_BASE_CODES,
  ...PROVIDER_SPECIFIC_FAILURE_CODES,
] as const;

export type PublicationFailureCode = (typeof PUBLICATION_FAILURE_CODES)[number];

export const publicationFailureCodeSchema = z.enum(PUBLICATION_FAILURE_CODES);
