import type { Locale } from "@rz-chain-reporter/i18n";

const PRODUCT_HELP: Record<Locale, readonly string[]> = {
  en: [
    "The assistant explains shipped workspace behavior and the selected customer's reviewed guidance, and can inspect bounded operator-owned Editorial, Account, Usage, Saved, Publishing, and enabled Market Analysis records through their existing read owners.",
    "Editorial workflow: 1. On Multi Media (/dashboard), configure one News or Promo run and start it. 2. Review Model and Telegram lanes. On an origin card, Send to <platform> creates a routed Platform Lane card and starts automatic copy generation; an existing route opens its current card. Wait for the generated candidates. 3. In Card Sheet, choose a generated copy style, edit the headline, body, and hashtags, then create a revision or select an existing revision. 4. To regenerate later, use Regenerate, or Refresh article and regenerate when an RSS item needs its full article; wait for the new candidates, choose one, re-edit if needed, and create the new current revision. 5. Generate, upload, select, replace, or remove an image for that exact active revision when needed; an image is optional for Telegram and X but required for Instagram. 6. Approve the exact active revision and image, then publish now or schedule it. Account (/account), Saved (/saved), and Schedule (/schedule) reopen the same Card Sheet; after any regeneration, edit, or revision change, repeat the candidate, revision, image, and approval checks and approve the changed revision before publishing.",
    "Market Analysis workflow, when enabled: 1. On Market Analysis (/market-analysis), choose one to three primary instruments, zero to three Binance comparisons, period, scale, output format, and content language; review the summary and fetch verified prices. 2. In Market, review the verified series. 3. In Chart, configure and approve the chart. 4. In Story, edit and approve the text. 5. In Design, choose and approve the layout. 6. In Generate, create and approve the final image. 7. In Publish, choose a platform and editorial model, press Generate 3 caption options, choose or edit one, prepare its draft, and then save, schedule, or publish it. Changing an upstream stage clears the affected downstream approvals and artifacts, so continue again from the first affected stage before publishing.",
    "Account (/account) shows the operator profile, counts, recent activity and topics, saved cards, and schedules. Saved (/saved) redirects to Account with its filter and cursor preserved. Usage (/usage) supports rolling 24-hour, 7-day, 30-day, or all-time filters plus model, backend, provider, task, and status; its summary shows invocations, tokens, recorded cost, and model breakdown, while the ledger shows individual calls. Publishing on Schedule (/schedule) separates scheduled, published, and reconciliation views and owns cancel, reschedule, recovery, retry, reconciliation, and publishing pause controls.",
    "Sources (/sources) owns source imports and their evidence, and it is desk-only in the assistant. Open Sources, choose enabled RSS or public Telegram sources, a recency window, and enrichment. When Telegram sources are selected, also choose chronological or keyword ordering, the shortlist size, and any keyword topics, then start one import. The current and recent import cards show per-source outcomes and counts; the catalog shows lifecycle, endpoint, locale, fetch mode, and latest observation; the item stream filters the imported items and their admission or enrichment path.",
    "It can prepare one News or Promo run from conversation, retain known values, ask one material question at a time, and show a complete preview. Only the preview's explicit Approve control can start that run.",
    "When Market Analysis is enabled, it can prepare one new analysis from conversation, ask for each missing setup value, and show a complete preview. Only the preview's explicit Approve control can create it; every later Market stage stays in the Market Analysis workspace.",
    "Editorial and Card Sheet changes stay in Multi Media. Content approval, publishing, and scheduling stay in the Card Sheet, Saved, or Schedule; cancel and reschedule from the Schedule desk. The assistant cannot perform those effects, check provider health, run arbitrary database queries, export data, search the external web, or perform multi-item write batches.",
    "Usage supports rolling periods: the last 24 hours, 7 days, 30 days, or all time. A calendar-day ‘yesterday’ is not available. Ask whether the operator would like the last 24 hours, and do not run a read until they explicitly choose it.",
  ],
  fa: [
    "دستیار رفتارهای عرضه‌شدهٔ محیط کار و راهنمای بازبینی‌شدهٔ مشتری انتخاب‌شده را توضیح می‌دهد و می‌تواند رکوردهای محدود و متعلق به اپراتور را در تحریریه، حساب، مصرف، ذخیره‌شده‌ها، انتشار و تحلیل بازار فعال از مسیر خواندن موجود همان بخش بررسی کند.",
    "روند میز تحریریه: ۱. در «چند رسانه» (/dashboard) یک اجرای خبری یا تبلیغی را تنظیم و با «شروع اجرا» آغاز کنید. ۲. «خط‌های مدل» و «خط‌های منبع تلگرام» را بازبینی کنید. در کارت مبدأ، «ارسال به پلتفرم» یک کارت در «خط‌های پلتفرم» می‌سازد و تولید خودکار متن را آغاز می‌کند؛ مسیر موجود همان کارت فعلی را باز می‌کند. تا آماده‌شدن تنوع‌های تولیدشده صبر کنید. ۳. در «پیش‌نمایش پنل» یک سبک متن را انتخاب کنید، تیتر، متن و هشتگ‌ها را ویرایش کنید و سپس بازبینی جدید را بسازید یا یک بازبینی موجود را انتخاب کنید. ۴. برای تولید دوباره، «تولید دوباره» را بزنید؛ اگر قلم آر‌اس‌اس به متن کامل مقاله نیاز دارد، «تازه‌سازی مقاله و تولید دوباره» را بزنید. پس از آماده‌شدن تنوع‌های جدید، یکی را انتخاب کنید، در صورت نیاز دوباره ویرایش کنید و بازبینی جاری تازه‌ای بسازید. ۵. در صورت نیاز، تصویر همان بازبینی فعال را تولید، بارگذاری، انتخاب، تعویض یا حذف کنید؛ تصویر برای تلگرام و ایکس اختیاری است اما برای اینستاگرام لازم است. ۶. همان بازبینی و تصویر فعال را تأیید و سپس اکنون منتشر یا زمان‌بندی کنید. «حساب» (/account)، «ذخیره‌ها» (/saved) و «زمان‌بندی» (/schedule) همان «پیش‌نمایش پنل» را دوباره باز می‌کنند؛ پس از هر تولید دوباره، ویرایش یا تغییر بازبینی، انتخاب متن، ساخت بازبینی، تصویر و تأیید را دوباره بررسی کنید و پیش از انتشار بازبینی تغییریافته را تأیید کنید.",
    "روند تحلیل بازار، در صورت فعال‌بودن: ۱. در «تحلیل بازار» (/market-analysis) یک تا سه ابزار اصلی، صفر تا سه مقایسهٔ بایننس، دوره، مقیاس، قالب خروجی و زبان محتوا را انتخاب کنید، خلاصه را بازبینی کنید و قیمت‌های تأییدشده را بگیرید. ۲. در «بازار» سری‌های تأییدشده را ببینید. ۳. در «نمودار» نمودار را تنظیم و تأیید کنید. ۴. در «روایت» متن را ویرایش و تأیید کنید. ۵. در «طراحی» چیدمان را انتخاب و تأیید کنید. ۶. در «تولید» تصویر نهایی را بسازید و تأیید کنید. ۷. در «انتشار» پلتفرم و مدل تحریریه را انتخاب کنید، «ساخت ۳ گزینهٔ کپشن» را بزنید، یکی را انتخاب یا ویرایش کنید، پیش‌نویس را آماده کنید و سپس ذخیره، زمان‌بندی یا منتشر کنید. تغییر یک مرحلهٔ بالادستی، تأییدها و خروجی‌های وابستهٔ مراحل بعدی را پاک می‌کند؛ پیش از انتشار از نخستین مرحلهٔ متأثر دوباره ادامه دهید.",
    "«حساب» (/account) نمایهٔ اپراتور، آمار، فعالیت‌ها و موضوع‌های اخیر، کارت‌های ذخیره‌شده و زمان‌بندی‌ها را نشان می‌دهد. «ذخیره‌ها» (/saved) با حفظ فیلتر و نشانگر صفحه به «حساب» هدایت می‌شود. «مصرف» (/usage) بازه‌های شناور ۲۴ ساعت، ۷ روز، ۳۰ روز یا همهٔ زمان‌ها و فیلترهای مدل، پشتوانه، ارائه‌دهنده، وظیفه و وضعیت را دارد؛ «خلاصهٔ دوره» تعداد فراخوانی، توکن، هزینهٔ ثبت‌شده و تفکیک مدل را نشان می‌دهد و «دفتر مصرف» جزئیات هر فراخوانی را نمایش می‌دهد. «زمان‌بندی» (/schedule) نماهای زمان‌بندی‌شده، منتشرشده و تطبیق و کنترل‌های لغو، زمان‌بندی دوباره، بازیابی، تلاش دوباره، تطبیق و توقف انتشار را در اختیار دارد.",
    "«منابع» (/sources) مالک واردکردن منابع و شواهد آن است و در دستیار فقط از مسیر میز خودش راهنمایی می‌شود. «منابع» را باز کنید، منابع فعال آر‌اس‌اس یا تلگرام عمومی، بازهٔ تازگی و غنی‌سازی را انتخاب کنید. اگر منبع تلگرام انتخاب شده، ترتیب زمانی یا کلیدواژه‌ای، اندازهٔ فهرست نهایی و موضوع‌های کلیدواژه را هم تعیین کنید و سپس یک واردسازی را آغاز کنید. کارت‌های واردسازی جاری و اخیر، نتیجه و شمارش هر منبع را نشان می‌دهند؛ فهرست منابع چرخهٔ عمر، نشانی، زبان، روش واکشی و آخرین مشاهده را نمایش می‌دهد؛ جریان قلم‌ها نیز قلم‌های واردشده و مسیر پذیرش یا غنی‌سازی آن‌ها را فیلتر می‌کند.",
    "دستیار می‌تواند یک اجرای خبر یا تبلیغاتی را در گفت‌وگو آماده کند، مقدارهای معلوم را نگه دارد، هر بار فقط یک پرسش مهم بپرسد و پیش‌نمایش کامل نشان دهد. فقط کنترل صریح تأیید در پیش‌نمایش می‌تواند اجرا را آغاز کند.",
    "وقتی «تحلیل بازار» فعال است، دستیار می‌تواند یک تحلیل جدید را در گفت‌وگو آماده کند، هر مقدار تنظیماتِ جاافتاده را بپرسد و پیش‌نمایش کامل نشان دهد. فقط کنترل صریح «تأیید» می‌تواند آن را بسازد؛ همهٔ مراحل بعدی در محیط «تحلیل بازار» انجام می‌شوند.",
    "تغییرهای تحریریه و «پیش‌نمایش پنل» در «چند رسانه» انجام می‌شوند. تأیید محتوا، انتشار و زمان‌بندی در «پیش‌نمایش پنل»، «ذخیره‌شده‌ها» یا «زمان‌بندی» انجام می‌شوند؛ لغو و زمان‌بندی دوباره نیز از میز «زمان‌بندی» است. دستیار نمی‌تواند این اثرها را اجرا کند، سلامت ارائه‌دهنده را بررسی کند، پرس‌وجوی دلخواه پایگاه داده انجام دهد، داده خروجی بگیرد، در وب بیرونی جست‌وجو کند یا چند عمل نوشتنی را گروهی انجام دهد.",
    "گزارش مصرف فقط بازه‌های شناور ۲۴ ساعت گذشته، ۷ روز گذشته، ۳۰ روز گذشته یا همهٔ زمان‌ها را پشتیبانی می‌کند. «دیروز» به‌معنای روز تقویمی در دسترس نیست. از اپراتور بپرسید آیا می‌خواهد ۲۴ ساعت گذشته را ببیند و تا انتخاب صریح او هیچ خواندنی اجرا نکنید.",
  ],
};

export function productHelp(locale: Locale) {
  return PRODUCT_HELP[locale];
}
