import { MAX_REFERENCE_IMAGE_BYTES } from "@rz-chain-reporter/contracts";

const MULTIPART_ENVELOPE_BYTES = 128 * 1024;

export const MAX_RPC_MULTIPART_BODY_BYTES =
  MAX_REFERENCE_IMAGE_BYTES + MULTIPART_ENVELOPE_BYTES;
